=== api-evangelist/amazon-qldb/json-schema/amazon-qldb-describe-ledger-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-qldb/refs/heads/main/json-schema/amazon-qldb-describe-ledger-response-schema.json",
  "title": "DescribeLedgerResponse",
  "description": "DescribeLedgerResponse schema from Amazon QLDB API",
  "type": "object",
  "properties": {
    "Name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LedgerName"
        },
        {
          "description": "The name of the ledger."
        }
      ]
    },
    "Arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Arn"
        },
        {
          "description": "The Amazon Resource Name (ARN) for the ledger."
        }
      ]
    },
    "State": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LedgerState"
        },
        {
          "description": "The current status of the ledger."
        }
      ]
    },
    "CreationDateTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": "The date and time, in epoch time format, when the ledger was created. (Epoch time format is the number of seconds elapsed since 12:00:00 AM January 1, 1970 UTC.)"
        }
      ]
    },
    "PermissionsMode": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PermissionsMode"
        },
        {
          "description": "The permissions mode of the ledger."
        }
      ]
    },
    "DeletionProtection": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DeletionProtection"
        },
        {
          "description": "<p>The flag that prevents a ledger from being deleted by any user. If not provided on ledger creation, this feature is enabled (<code>true</code>) by default.</p> <p>If deletion protection is enabled, you must first disable it before you can delete the ledger. You can disable it by calling the <code>UpdateLedger</code> operation to set the flag to <code>false</code>.</p>"
        }
      ]
    },
    "EncryptionDescription": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LedgerEncryptionDescription"
        },
        {
          "description": "Information about the encryption of data at rest in the ledger. This includes the current status, the KMS key, and when the key became inaccessible (in the case of an error)."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-qldb/examples/amazon-qldb-describe-ledger-response-example.json
{
  "Name": "my-ledger",
  "Arn": "arn:aws:qldb:us-east-1:123456789:ledger/my-ledger",
  "State": "example-State",
  "CreationDateTime": "2025-03-15T14:30:00Z",
  "PermissionsMode": "example-PermissionsMode",
  "DeletionProtection": "example-DeletionProtection",
  "EncryptionDescription": "example-EncryptionDescription"
}
